//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modulo_Boston.Pages {
    
    
    public partial class wbfrm_usuarios_por_grupo_de_acceso {
    }
}
