//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pages_names_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pages_names_es() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.pages_names_es", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contraseña.
        /// </summary>
        internal static string lbl_etiqueta_contrasena {
            get {
                return ResourceManager.GetString("lbl_etiqueta_contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de Usuario.
        /// </summary>
        internal static string lbl_etiqueta_usuario {
            get {
                return ResourceManager.GetString("lbl_etiqueta_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es la responsabilidad del Gerente de cada Dpto. asegurar que los activos fijos de su area de responsabilidad sean debidamente controlados, asi como de informar cualquier movimineto importante en los mismos al Dpto de Finanzas..
        /// </summary>
        internal static string lb_aviso {
            get {
                return ResourceManager.GetString("lb_aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cédula Jurídica.
        /// </summary>
        internal static string lb_cedula_juridica {
            get {
                return ResourceManager.GetString("lb_cedula_juridica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Costo.
        /// </summary>
        internal static string lb_centro_costo {
            get {
                return ResourceManager.GetString("lb_centro_costo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centro de Costo Destino.
        /// </summary>
        internal static string lb_centro_costo_destino {
            get {
                return ResourceManager.GetString("lb_centro_costo_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacto.
        /// </summary>
        internal static string lb_contacto {
            get {
                return ResourceManager.GetString("lb_contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaro y garantizo que la cantidad de activos y equipos descrito en este formulario son los que realmente van en las cajas indicadas..
        /// </summary>
        internal static string lb_declaracion_jurada {
            get {
                return ResourceManager.GetString("lb_declaracion_jurada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de Destrucción de Activos Fijos.
        /// </summary>
        internal static string lb_destruccion_activos {
            get {
                return ResourceManager.GetString("lb_destruccion_activos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dirección Exacta de Proveedor.
        /// </summary>
        internal static string lb_direccion_exacta_proveedor {
            get {
                return ResourceManager.GetString("lb_direccion_exacta_proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        internal static string lb_fecha {
            get {
                return ResourceManager.GetString("lb_fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha aproximada de reingreso.
        /// </summary>
        internal static string lb_fecha_aprox_reingreso {
            get {
                return ResourceManager.GetString("lb_fecha_aprox_reingreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de Mantenimiento de Activos Fijos.
        /// </summary>
        internal static string lb_feildset_mantenimiento {
            get {
                return ResourceManager.GetString("lb_feildset_mantenimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información de Área Destino de los Activos Fíjos.
        /// </summary>
        internal static string lb_fieldset_area_destino {
            get {
                return ResourceManager.GetString("lb_fieldset_area_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de Calibración de Activos Fijos.
        /// </summary>
        internal static string lb_fieldset_calibracion {
            get {
                return ResourceManager.GetString("lb_fieldset_calibracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de Denuncia de Robo &amp; Pérdida de Activos Fijos.
        /// </summary>
        internal static string lb_fieldset_denuncia {
            get {
                return ResourceManager.GetString("lb_fieldset_denuncia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud de Donación de Activos Fijos.
        /// </summary>
        internal static string lb_fieldset_donacion {
            get {
                return ResourceManager.GetString("lb_fieldset_donacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Responsable Destino.
        /// </summary>
        internal static string lb_id_responsable_destino {
            get {
                return ResourceManager.GetString("lb_id_responsable_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Solicitante.
        /// </summary>
        internal static string lb_id_solicitante {
            get {
                return ResourceManager.GetString("lb_id_solicitante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localización.
        /// </summary>
        internal static string lb_localizacion_destino {
            get {
                return ResourceManager.GetString("lb_localizacion_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de Proceso OIJ.
        /// </summary>
        internal static string lb_numero_proceso {
            get {
                return ResourceManager.GetString("lb_numero_proceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones:.
        /// </summary>
        internal static string lb_observaciones {
            get {
                return ResourceManager.GetString("lb_observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones:.
        /// </summary>
        internal static string lb_observaciones_calibracion {
            get {
                return ResourceManager.GetString("lb_observaciones_calibracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favor detallar lo sucedido.
        /// </summary>
        internal static string lb_observaciones_denuncia {
            get {
                return ResourceManager.GetString("lb_observaciones_denuncia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        internal static string lb_observaciones_solicitud {
            get {
                return ResourceManager.GetString("lb_observaciones_solicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones:.
        /// </summary>
        internal static string lb_observacion_destruccion {
            get {
                return ResourceManager.GetString("lb_observacion_destruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones:.
        /// </summary>
        internal static string lb_observacion_mantenimiento {
            get {
                return ResourceManager.GetString("lb_observacion_mantenimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formulario para movimiento de Activo Fijo.
        /// </summary>
        internal static string lb_page_title {
            get {
                return ResourceManager.GetString("lb_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planta.
        /// </summary>
        internal static string lb_planta {
            get {
                return ResourceManager.GetString("lb_planta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planta.
        /// </summary>
        internal static string lb_planta_destino {
            get {
                return ResourceManager.GetString("lb_planta_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proveedor.
        /// </summary>
        internal static string lb_proveedor {
            get {
                return ResourceManager.GetString("lb_proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable.
        /// </summary>
        internal static string lb_responsable {
            get {
                return ResourceManager.GetString("lb_responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Responsable.
        /// </summary>
        internal static string lb_responsable_destino {
            get {
                return ResourceManager.GetString("lb_responsable_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sección.
        /// </summary>
        internal static string lb_seccion_destino {
            get {
                return ResourceManager.GetString("lb_seccion_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitud #.
        /// </summary>
        internal static string lb_solicitud {
            get {
                return ResourceManager.GetString("lb_solicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfono.
        /// </summary>
        internal static string lb_telefono {
            get {
                return ResourceManager.GetString("lb_telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Movimiento.
        /// </summary>
        internal static string lb_tipo_movimiento {
            get {
                return ResourceManager.GetString("lb_tipo_movimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Declaracion Jurada.
        /// </summary>
        internal static string lb_titulo_declaracion_jurada {
            get {
                return ResourceManager.GetString("lb_titulo_declaracion_jurada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación.
        /// </summary>
        internal static string lb_ubicacion_destino {
            get {
                return ResourceManager.GetString("lb_ubicacion_destino", resourceCulture);
            }
        }
    }
}
