//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile el proyecto de Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pages_names_es {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pages_names_es() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.pages_names_es", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Invalida la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        internal static string lbl_etiqueta_contrasena {
            get {
                return ResourceManager.GetString("lbl_etiqueta_contrasena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de Usuario.
        /// </summary>
        internal static string lbl_etiqueta_usuario {
            get {
                return ResourceManager.GetString("lbl_etiqueta_usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Es la responsabilidad del Gerente de cada Dpto. asegurar que los activos fijos de su area de responsabilidad sean debidamente controlados, asi como de informar cualquier movimineto importante en los mismos al Dpto de Finanzas..
        /// </summary>
        internal static string lb_aviso {
            get {
                return ResourceManager.GetString("lb_aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cédula Jurídica.
        /// </summary>
        internal static string lb_cedula_juridica {
            get {
                return ResourceManager.GetString("lb_cedula_juridica", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro de Costo.
        /// </summary>
        internal static string lb_centro_costo {
            get {
                return ResourceManager.GetString("lb_centro_costo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Centro de Costo Destino.
        /// </summary>
        internal static string lb_centro_costo_destino {
            get {
                return ResourceManager.GetString("lb_centro_costo_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contacto.
        /// </summary>
        internal static string lb_contacto {
            get {
                return ResourceManager.GetString("lb_contacto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Declaro y garantizo que la cantidad de activos y equipos descrito en este formulario son los que realmente van en las cajas indicadas..
        /// </summary>
        internal static string lb_declaracion_jurada {
            get {
                return ResourceManager.GetString("lb_declaracion_jurada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Destrucción de Activos Fijos.
        /// </summary>
        internal static string lb_destruccion_activos {
            get {
                return ResourceManager.GetString("lb_destruccion_activos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección Exacta de Proveedor.
        /// </summary>
        internal static string lb_direccion_exacta_proveedor {
            get {
                return ResourceManager.GetString("lb_direccion_exacta_proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha.
        /// </summary>
        internal static string lb_fecha {
            get {
                return ResourceManager.GetString("lb_fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fecha aproximada de reingreso.
        /// </summary>
        internal static string lb_fecha_aprox_reingreso {
            get {
                return ResourceManager.GetString("lb_fecha_aprox_reingreso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Mantenimiento de Activos Fijos.
        /// </summary>
        internal static string lb_feildset_mantenimiento {
            get {
                return ResourceManager.GetString("lb_feildset_mantenimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información de Área Destino de los Activos Fíjos.
        /// </summary>
        internal static string lb_fieldset_area_destino {
            get {
                return ResourceManager.GetString("lb_fieldset_area_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Calibración de Activos Fijos.
        /// </summary>
        internal static string lb_fieldset_calibracion {
            get {
                return ResourceManager.GetString("lb_fieldset_calibracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Denuncia de Robo &amp; Pérdida de Activos Fijos.
        /// </summary>
        internal static string lb_fieldset_denuncia {
            get {
                return ResourceManager.GetString("lb_fieldset_denuncia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud de Donación de Activos Fijos.
        /// </summary>
        internal static string lb_fieldset_donacion {
            get {
                return ResourceManager.GetString("lb_fieldset_donacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Usuario.
        /// </summary>
        internal static string lb_id_responsable_destino {
            get {
                return ResourceManager.GetString("lb_id_responsable_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ID Solicitante.
        /// </summary>
        internal static string lb_id_solicitante {
            get {
                return ResourceManager.GetString("lb_id_solicitante", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Localización.
        /// </summary>
        internal static string lb_localizacion_destino {
            get {
                return ResourceManager.GetString("lb_localizacion_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de Proceso OIJ.
        /// </summary>
        internal static string lb_numero_proceso {
            get {
                return ResourceManager.GetString("lb_numero_proceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones:.
        /// </summary>
        internal static string lb_observaciones {
            get {
                return ResourceManager.GetString("lb_observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones:.
        /// </summary>
        internal static string lb_observaciones_calibracion {
            get {
                return ResourceManager.GetString("lb_observaciones_calibracion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Favor detallar lo sucedido.
        /// </summary>
        internal static string lb_observaciones_denuncia {
            get {
                return ResourceManager.GetString("lb_observaciones_denuncia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones.
        /// </summary>
        internal static string lb_observaciones_solicitud {
            get {
                return ResourceManager.GetString("lb_observaciones_solicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones:.
        /// </summary>
        internal static string lb_observacion_destruccion {
            get {
                return ResourceManager.GetString("lb_observacion_destruccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Observaciones:.
        /// </summary>
        internal static string lb_observacion_mantenimiento {
            get {
                return ResourceManager.GetString("lb_observacion_mantenimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema de aprobación de movimientos para Activos Fijos.
        /// </summary>
        internal static string lb_page_title {
            get {
                return ResourceManager.GetString("lb_page_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sistema de aprobación de movimientos para Activos Fijos.
        /// </summary>
        internal static string lb_page_title_login {
            get {
                return ResourceManager.GetString("lb_page_title_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planta.
        /// </summary>
        internal static string lb_planta {
            get {
                return ResourceManager.GetString("lb_planta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Planta.
        /// </summary>
        internal static string lb_planta_destino {
            get {
                return ResourceManager.GetString("lb_planta_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Proveedor.
        /// </summary>
        internal static string lb_proveedor {
            get {
                return ResourceManager.GetString("lb_proveedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        internal static string lb_responsable {
            get {
                return ResourceManager.GetString("lb_responsable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Responsable.
        /// </summary>
        internal static string lb_responsable_destino {
            get {
                return ResourceManager.GetString("lb_responsable_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sección.
        /// </summary>
        internal static string lb_seccion_destino {
            get {
                return ResourceManager.GetString("lb_seccion_destino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitud #.
        /// </summary>
        internal static string lb_solicitud {
            get {
                return ResourceManager.GetString("lb_solicitud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono.
        /// </summary>
        internal static string lb_telefono {
            get {
                return ResourceManager.GetString("lb_telefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Movimiento.
        /// </summary>
        internal static string lb_tipo_movimiento {
            get {
                return ResourceManager.GetString("lb_tipo_movimiento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Declaracion Jurada.
        /// </summary>
        internal static string lb_titulo_declaracion_jurada {
            get {
                return ResourceManager.GetString("lb_titulo_declaracion_jurada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ubicación.
        /// </summary>
        internal static string lb_ubicacion_destino {
            get {
                return ResourceManager.GetString("lb_ubicacion_destino", resourceCulture);
            }
        }
    }
}
